---
development:
  cloud_name: carmenhchung
  api_key: '835761933113777'
  api_secret: IN7w0Mdi2XMegHkSemqg_rROuyY
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: carmenhchung
  api_key: '835761933113777'
  api_secret: IN7w0Mdi2XMegHkSemqg_rROuyY
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: carmenhchung
  api_key: '835761933113777'
  api_secret: IN7w0Mdi2XMegHkSemqg_rROuyY
  enhance_image_tag: true
  static_image_support: false
