development:
  cloud_name: "carmenhchung",
  api_key: ENV["CLOUDINARY_KEY"],
  api_secret: ENV["CLOUDINARY_SERCRET"]


test:
  cloud_name: "carmenhchung",
  api_key: ENV["CLOUDINARY_KEY"],
  api_secret: ENV["CLOUDINARY_SERCRET"]
